theme: jekyll-theme-minimal
title: Thrupthi Ann John
logo: /assets/img/profile.png
description: In theory, there is no difference between theory and practice, while in practice, there is.
show_downloads: false
